name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install udunits
      run: |
        cd /opt
        curl -O https://downloads.unidata.ucar.edu/udunits/2.2.28/udunits-2.2.28.tar.gz
        tar -xzvf udunits-2.2.28.tar.gz
        cd udunits-2.2.28
        ./configure
        make all install
        ln -sf /opt/lib/* $LD_LIBRARY_PATH
    - name: Install exiftool and netcdf
      run: |
        sudo apt install libimage-exiftool-perl -y
        sudo apt-get install -y netcdf-bin
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Test with pytest
      run: |
        export UDUNITS2_XML_PATH=/opt/share/udunits/udunits2.xml
        python -m pytest -v tests/test_readers.py tests/test_rules.py tests/test_show_specs.py tests/test_images.py tests/test_generic.py tests/test_utils.py tests/test_ncas_file_proc.py tests/test_cvs.py
